### ISSUE TITLE
cfncluster with python3

### ISSUE THREAD

**Issue by bcthomas** [awslabs/cfncluster#157]
I left this as a comment on #78 and wondered if I could get some help.

I cannot get cfncluster to work with 3.5.2 (works fine with 2.7).  Is this a known issue?  The only requirements I see in the docs where it specifically says 2.7 is for the windows section (I'm using both os x and a modern linux).  If 3.5.2 is not supported, are there plans to?

Just for reference, here is the situation (for os x)...
```
# pyenv version
3.5.2 (set by /Users/bct/.pyenv/version)
# pip install cfncluster --upgrade
Requirement already up-to-date: cfncluster in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages
Requirement already up-to-date: boto>=2.42.0 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from cfncluster)
Requirement already up-to-date: awscli>=1.10.56 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from cfncluster)
Requirement already up-to-date: botocore==1.4.92 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: PyYAML<=3.12,>=3.10 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: colorama<=0.3.7,>=0.2.5 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: docutils>=0.10 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: s3transfer<0.2.0,>=0.1.9 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: rsa<=3.5.0,>=3.1.2 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from awscli>=1.10.56->cfncluster)
Requirement already up-to-date: python-dateutil<3.0.0,>=2.1 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from botocore==1.4.92->awscli>=1.10.56->cfncluster)
Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from botocore==1.4.92->awscli>=1.10.56->cfncluster)
Requirement already up-to-date: pyasn1>=0.1.3 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from rsa<=3.5.0,>=3.1.2->awscli>=1.10.56->cfncluster)
Requirement already up-to-date: six>=1.5 in ~/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.4.92->awscli>=1.10.56->cfncluster)
# cfncluster configure
Traceback (most recent call last):
  File "~/.pyenv/versions/3.5.2/bin/cfncluster", line 11, in <module>
    load_entry_point('cfncluster==1.3.1', 'console_scripts', 'cfncluster')()
  File "~/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cfncluster/cli.py", line 154, in main
    args.func(args)
  File "~/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cfncluster/cli.py", line 25, in configure
    easyconfig.configure(args)
AttributeError: module 'easyconfig' has no attribute 'configure'
```

**Comment by snorfalorpagus** [comment]
I have the same problem, running Python 3.5.1 with Anaconda on OS X.

You also get an error if you call `cfncluster` without any arguments:

```
snorfmac:~ snorf$ cfncluster
Traceback (most recent call last):
  File "/Users/snorf/miniconda3/bin/cfncluster", line 11, in <module>
    sys.exit(main())
  File "/Users/snorf/miniconda3/lib/python3.5/site-packages/cfncluster/cli.py", line 154, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by snorfalorpagus** [comment]
Confirmed the same issue running Python 3.4.4 on Windows 7.

**Comment by dougalb** [comment]
Updates to support Python 3 have been pushed to https://github.com/awslabs/cfncluster/tree/develop. Please clone/pull/download and test.

**Comment by snorfalorpagus** [comment]
I successfully used the develop branch to create, use and delete a cluster today on Python 3.

**Comment by bcthomas** [comment]
@dougalb Success. Tested with 3.5.2 with no problems.

```
#Clone repo, check out develop branch
cd cli
pip install -r requirements.txt
pip install -e .
```

Thanks!

**Comment by snorfalorpagus** [comment]
I've been using this for a little while now without any problems. Running on Python 3.6 now.

**Comment by bwbarrett** [comment]
It sounds like this is fixed, so resolving this ticket.  Please re-open if there are still problems we missed.
