### ISSUE TITLE
using post_install to mount a EBS volume question

### ISSUE THREAD

**Issue by bcthomas** [awslabs/cfncluster#172]
I'm trying mount a EBS volume by volume name like so...
mount_data.sh contents
```
#!/bin/bash
 
. /etc/cfncluster/cfnconfig
 
mkdir /data
 
if [ "$cfn_node_type" == "MasterServer" ]; then
/usr/local/sbin/attachVolume.py $1
mount /dev/disk/by-ebs-volumeid/$1 /data
exportfs -o rw,no_root_squash '*':/data
fi
 
if [ "$cfn_node_type" == "ComputeFleet" ]; then
mount $cfn_master:/data /data
fi
```

cfncluster config file
```
post_install = http://mg-post-install-scripts.s3.amazonaws.com/mount_data.sh
post_install_args = vol-00ddaf8d8e0db149f
s3_read_resource = *
```

Master node boots and creates the directory, but then I get the following error in cfn-inig.log...

```
Traceback (most recent call last):
  File "/usr/local/sbin/attachVolume.py", line 36, in <module>
    conn.attach_volume(volumeId,instanceId,dev)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 2377, in attach_volume
    return self.get_status('AttachVolume', params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Value (http://mg-post-install-scripts.s3.amazonaws.com/mount_data.sh) for parameter volume is invalid. Expected: 'vol-...'.</Message></Error></Errors><RequestID>c80433cf-b194-44c4-af3d-2f90d989a5d7</RequestID></Response>
mount.nfs: Failed to resolve server /dev/disk/by-ebs-volumeid/http: Name or service not known
```

Anyone have an idea what i'm missing? I've tried using `http`, `https`, and the `s3` url form and they all give this error.

Thanks

**Comment by bcthomas** [comment]
I just realized this is a duplicate of #139

**Comment by bcthomas** [comment]
Adding some details...  I'm using cfncluster version 1.3.1 and python3 (3.5.2).  After reading #139, I switched my `mount_data.sh` script to use `$2`.  This allowed me to get past the above error, but subsequently I now am getting this...

```2017-03-03 16:50:24,390 [DEBUG] Command runpostinstall output: mount: special device /dev/disk/by-ebs-volumeid/vol-00dddf8f8e0fb149c does not exist```

However, running this command after the master node is up shows the volume is attached...

```sudo /usr/local/sbin/attachVolume.py vol-00dddf8f8e0fb149c
Traceback (most recent call last):
  File "/usr/local/sbin/attachVolume.py", line 36, in <module>
    conn.attach_volume(volumeId,instanceId,dev)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 2377, in attach_volume
    return self.get_status('AttachVolume', params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>VolumeInUse</Code><Message>vol-00dddf8f8e0fb149c is already attached to an instance</Message></Error></Errors><RequestID>da9ddfe2-74fb-4762-9204-6df429c429bb</RequestID></Response>
```

and mounting it with...

```sudo mount /dev/disk/by-ebs-volumeid/vol-00dddf8f8e0fb149c /data```

works fine as well.

Anyone have any idea why it's failing as a `post_install` action?

Thanks.

**Comment by bcthomas** [comment]
OK - workaround!  I thought this seemed like possibly a timing issue, so I changed my startup script to include a `sleep` statement...

```
#!/bin/bash
 
. /etc/cfncluster/cfnconfig
 
if [ "$cfn_node_type" == "MasterServer" ]; then
/usr/local/sbin/attachVolume.py $2
sleep 20
mount /dev/disk/by-ebs-volumeid/$2 /data
exportfs -o rw,no_root_squash '*':/data
fi
 
if [ "$cfn_node_type" == "ComputeFleet" ]; then
mount $cfn_master:/data /data
fi
```

This worked perfectly, in case it helps anyone else.

Cheers.

**Comment by mohanasudhan** [comment]
Why can't you use http://cfncluster.readthedocs.io/en/latest/configuration.html#ebs ?

**Comment by bcthomas** [comment]
@mohanasudhan i'm not sure i understand - I'm already using that configuration for the shared ebs volume. This issue relates to adding a second ebs volume (domain specific data needed on all nodes).
