### ISSUE TITLE
Master fails with selinux (CIS aws ami)

### ISSUE THREAD

**Issue by shadycuz** [awslabs/cfncluster#220]
```
[root@ip-10-0-0-5 log]# tail -n 100 cfn-init.log
Vendoring hostsfile (3.0.1) to /etc/chef/cookbooks/hostsfile
Vendoring iptables (4.2.0) to /etc/chef/cookbooks/iptables
Vendoring line (0.6.3) to /etc/chef/cookbooks/line
Vendoring mingw (2.0.1) to /etc/chef/cookbooks/mingw
Vendoring nfs (2.3.1) to /etc/chef/cookbooks/nfs
Vendoring ohai (5.2.0) to /etc/chef/cookbooks/ohai
Vendoring openssh (2.4.1) to /etc/chef/cookbooks/openssh
Vendoring poise (2.8.1) to /etc/chef/cookbooks/poise
Vendoring poise-archive (1.5.0) to /etc/chef/cookbooks/poise-archive
Vendoring poise-languages (2.1.1) to /etc/chef/cookbooks/poise-languages
Vendoring poise-python (1.6.0) to /etc/chef/cookbooks/poise-python
Vendoring seven_zip (2.0.2) to /etc/chef/cookbooks/seven_zip
Vendoring tar (2.0.0) to /etc/chef/cookbooks/tar
Vendoring windows (3.1.2) to /etc/chef/cookbooks/windows
Vendoring yum (5.0.1) to /etc/chef/cookbooks/yum
Vendoring yum-epel (2.1.2) to /etc/chef/cookbooks/yum-epel

2017-08-23 14:16:21,705 [DEBUG] No services specified
2017-08-23 14:16:21,706 [INFO] Running config chefPrepEnv
2017-08-23 14:16:21,707 [DEBUG] No packages specified
2017-08-23 14:16:21,707 [DEBUG] No groups specified
2017-08-23 14:16:21,707 [DEBUG] No users specified
2017-08-23 14:16:21,707 [DEBUG] No sources specified
2017-08-23 14:16:21,707 [DEBUG] No files specified
2017-08-23 14:16:21,707 [DEBUG] Running command chef
2017-08-23 14:16:21,707 [DEBUG] No test for command chef
2017-08-23 14:16:26,566 [ERROR] Command chef (chef-client --local-mode --config /etc/chef/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist cfncluster::_prep_env) failed
2017-08-23 14:16:26,566 [DEBUG] Command chef output: [2017-08-23T14:16:23+00:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.19.36
[2017-08-23T14:16:23+00:00] INFO: *** Chef 12.19.36 ***
[2017-08-23T14:16:23+00:00] INFO: Platform: x86_64-linux
[2017-08-23T14:16:23+00:00] INFO: Chef-client pid: 13827
[2017-08-23T14:16:26+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/nodes/ip-10-0-0-5.ec2.internal
[2017-08-23T14:16:26+00:00] INFO: Setting the run_list to recipe[cfncluster::sge_config] from CLI options
[2017-08-23T14:16:26+00:00] WARN: Run List override has been provided.
[2017-08-23T14:16:26+00:00] WARN: Original Run List: [recipe[cfncluster::sge_config]]
[2017-08-23T14:16:26+00:00] WARN: Overridden Run List: [recipe[cfncluster::_prep_env]]
[2017-08-23T14:16:26+00:00] INFO: Run List is [recipe[cfncluster::_prep_env]]
[2017-08-23T14:16:26+00:00] INFO: Run List expands to [cfncluster::_prep_env]
[2017-08-23T14:16:26+00:00] INFO: Starting Chef Run for ip-10-0-0-5.ec2.internal
[2017-08-23T14:16:26+00:00] INFO: Running start handlers
[2017-08-23T14:16:26+00:00] INFO: Start handlers complete.
[2017-08-23T14:16:26+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found:
resolving cookbooks for run list: ["cfncluster::_prep_env"]
[2017-08-23T14:16:26+00:00] INFO: HTTP Request Returned 412 Precondition Failed: No such cookbook: selinux

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
No such cookbook: selinux

Expanded Run List:
------------------
* cfncluster::_prep_env

Platform:
---------
x86_64-linux


Running handlers:
[2017-08-23T14:16:26+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-08-23T14:16:26+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 03 seconds
[2017-08-23T14:16:26+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2017-08-23T14:16:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-08-23T14:16:26+00:00] ERROR: 412 "Precondition Failed"
[2017-08-23T14:16:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

2017-08-23 14:16:26,566 [ERROR] Error encountered during build of chefPrepEnv: Command chef failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
2017-08-23 14:16:26,571 [ERROR] -----------------------BUILD FAILED!------------------------
2017-08-23 14:16:26,573 [ERROR] Unhandled exception during build: Command chef failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command chef failed
```

I was trying to locate where it determined that platform, so I could overide it to run the alpine cookbook, but I couldn't find it.

**Comment by mohanasudhan** [comment]
I like to reproduce the issue. with the latest version, i see successful execution of selinux cookbook. Please share your create comment and cfnconfig details <hide credential details if you have>

**Comment by shadycuz** [comment]
@mohanasudhan 
```
[aws]
aws_region_name = us-east-1

[vpc GalaxyVPC]
vpc_id = vpc-0d040b74
master_subnet_id = subnet-5b89a577
compute_subnet_id = subnet-6887ab44
use_public_ips = false

[global]
update_check = true
sanity_check = true
cluster_template = Galaxy

[cluster Galaxy]
vpc_settings = GalaxyVPC
custom_ami = ami-733a0c64
compute_instance_type = r4.2xlarge
master_instance_type = m4.large
key_name = xxxxxxxx
scheduler = slurm
cluster_type = ondemand
initial_queue_size = 1
maintain_initial_size = true
post_install = xxxxxxxxxxxxxxxxxxx
shared_dir = /export
compute_root_volume_size = 200
ebs_settings = custom
[ebs custom]
volume_size = 1000
volume_type = gp2
```

`cfncluster create Galaxy --norollback`

**Comment by shadycuz** [comment]
@mohanasudhan you get a chance to look at this?

**Comment by shadycuz** [comment]
@bwbarrett Hate to tag you personally like this but maybe it's something simple like I'm just not using the proper AMI.

**Comment by mohanasudhan** [comment]
Looking now.

**Comment by shadycuz** [comment]
Thanks

**Comment by mohanasudhan** [comment]
@shadycuz seems you are using ami from https://aws.amazon.com/marketplace/pp/B01K5UBMTW  In order to use custom ami pls follow the steps here for creating those ami http://cfncluster.readthedocs.io/en/latest/ami_customization.html?highlight=custom_ami
or 
https://github.com/awslabs/cfncluster/blob/develop/docs/source/ami_development.rst

I am not sure marketplace ami (ami-733a0c64) built to support in cfncluster

**Comment by shadycuz** [comment]
@mohanasudhan yes I didn't see that document on custom ami.

So I have to use the base AMI and harden it with something like an ansible playbook first? What is special about the base ami that I can't install the needed packages with userdate? 

Thanks @mohanasudhan

**Comment by mohanasudhan** [comment]
Refer https://github.com/awslabs/cfncluster-cookbook/blob/develop/build_ami.sh which is ami build script which basically invokes packer https://github.com/awslabs/cfncluster-cookbook/blob/develop/packer_centos7.json (centos7 example) -> ebs mapping, chef, ridley installation

**Comment by shadycuz** [comment]
Thanks @mohanasudhan Closing
