### ISSUE TITLE
centos 6 not registering new nodes

### ISSUE THREAD

**Issue by chriskeraly** [awslabs/cfncluster#281]
It seems as though, with the update on cfncluster, clusters built using centos6 aren't able to have new nodes added to their host list. It looks like maybe a new version of paramiko is not compatible.

Here is my config. It used to work fine.

```[cluster test]
vpc_settings = testvpc
key_name = xxx
master_instance_type=t2.micro
compute_instance_type=t2.micro
base_os=centos6
```

 Here is the error in ` /var/log/sqswatcher` on master

```[centos@ip-172-31-47-156 ~]$ cat /var/log/sqswatcher
2017-12-21 12:30:16,389 INFO [sqswatcher:main] sqswatcher startup
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. The next version of cryptography will drop support for Python 2.6
  DeprecationWarning
Traceback (most recent call last):
  File "/usr/bin/sqswatcher", line 9, in <module>
    load_entry_point('cfncluster-node==1.4.2', 'console_scripts', 'sqswatcher')()
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 211, in main
    pollQueue(scheduler, q, t)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 100, in pollQueue
    s = loadSchedulerModule(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 90, in loadSchedulerModule
    _scheduler = __import__(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/plugins/sge.py", line 15, in <module>
    import paramiko
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 89, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 103, in Transport
    _CLIENT_ID = 'paramiko_{}'.format(paramiko.__version__)
ValueError: zero length field name in format
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
2017-12-21 12:30:19,485 INFO [sqswatcher:main] sqswatcher startup
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. The next version of cryptography will drop support for Python 2.6
  DeprecationWarning
Traceback (most recent call last):
  File "/usr/bin/sqswatcher", line 9, in <module>
    load_entry_point('cfncluster-node==1.4.2', 'console_scripts', 'sqswatcher')()
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 211, in main
    pollQueue(scheduler, q, t)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 100, in pollQueue
    s = loadSchedulerModule(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 90, in loadSchedulerModule
    _scheduler = __import__(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/plugins/sge.py", line 15, in <module>
    import paramiko
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 89, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 103, in Transport
    _CLIENT_ID = 'paramiko_{}'.format(paramiko.__version__)
ValueError: zero length field name in format
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
2017-12-21 12:30:20,901 INFO [sqswatcher:main] sqswatcher startup
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. The next version of cryptography will drop support for Python 2.6
  DeprecationWarning
Traceback (most recent call last):
  File "/usr/bin/sqswatcher", line 9, in <module>
    load_entry_point('cfncluster-node==1.4.2', 'console_scripts', 'sqswatcher')()
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 211, in main
    pollQueue(scheduler, q, t)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 100, in pollQueue
    s = loadSchedulerModule(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 90, in loadSchedulerModule
    _scheduler = __import__(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/plugins/sge.py", line 15, in <module>
    import paramiko
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 89, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 103, in Transport
    _CLIENT_ID = 'paramiko_{}'.format(paramiko.__version__)
ValueError: zero length field name in format
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
2017-12-21 12:30:23,353 INFO [sqswatcher:main] sqswatcher startup
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. The next version of cryptography will drop support for Python 2.6
  DeprecationWarning
Traceback (most recent call last):
  File "/usr/bin/sqswatcher", line 9, in <module>
    load_entry_point('cfncluster-node==1.4.2', 'console_scripts', 'sqswatcher')()
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 211, in main
    pollQueue(scheduler, q, t)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 100, in pollQueue
    s = loadSchedulerModule(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 90, in loadSchedulerModule
    _scheduler = __import__(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/plugins/sge.py", line 15, in <module>
    import paramiko
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 89, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 103, in Transport
    _CLIENT_ID = 'paramiko_{}'.format(paramiko.__version__)
ValueError: zero length field name in format
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
2017-12-21 12:30:26,875 INFO [sqswatcher:main] sqswatcher startup
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. The next version of cryptography will drop support for Python 2.6
  DeprecationWarning
Traceback (most recent call last):
  File "/usr/bin/sqswatcher", line 9, in <module>
    load_entry_point('cfncluster-node==1.4.2', 'console_scripts', 'sqswatcher')()
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 211, in main
    pollQueue(scheduler, q, t)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 100, in pollQueue
    s = loadSchedulerModule(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/sqswatcher.py", line 90, in loadSchedulerModule
    _scheduler = __import__(scheduler)
  File "/usr/lib/python2.6/site-packages/sqswatcher/plugins/sge.py", line 15, in <module>
    import paramiko
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 89, in <module>
    class Transport(threading.Thread, ClosingContextManager):
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 103, in Transport
    _CLIENT_ID = 'paramiko_{}'.format(paramiko.__version__)
ValueError: zero length field name in format
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 81, in _join_lingering_threads
    for thr in _active_threads:
TypeError: 'NoneType' object is not iterable
[centos@ip-172-31-47-156 ~]$```

**Comment by chriskeraly** [comment]
Here is my config btw. It used to work fine.

[cluster test]
vpc_settings = testvpc
key_name = xxx
master_instance_type=t2.micro
compute_instance_type=t2.micro
base_os=centos6

**Comment by rajachan** [comment]
@chriskeraly that's right, Paramiko supports Python 2.7 and above only.  We will look into handling this better for CentOS6. Meanwhile, can you try upgrading to Python 2.7 on your nodes and see if that resolves the issue?

**Comment by bwbarrett** [comment]
@chriskeraly, it looks like we accidentally broke CentOS 6 for all the scheduler options in CfnCluster 1.4.0 and CfnCluster 1.4.1.  We're working on a fix, but due to the US holidays, it is unlikely that we will be able to release a patch before the first of the year.

There aren't any great options to work around the issue, but a couple of them are:

* Downgrade to CfnCluster 1.3.2, which will use an older version of the node-level package without this issue.  However, CfnCluster doesn't work on C5, M5, or a couple other recent instance families.
* Use an OS other than CentOS 6 (CentOS 7 will work).
* Theoretically, you could take our CentOS6 AMI, downgrade the paramiko package, and build a custom AMI for use with CfnCluster.  But there's a lot of hacking in that, so if you're not really comfortable building AMIs or using Chef, I'm not sure I'd go down that path.

**Comment by chriskeraly** [comment]
I downgraded to 1.3.2 and had it working for a little bit, but after a little work everything now crashes when I try and create the cluster, even without centos6:

```cfncluster create test3
2017-12-22T09:16:14.219 - INFO - cfncluster.cli - CfnCluster cli starting
2017-12-22T09:16:14.225 - INFO - cfncluster.cfncluster - Beginning cluster creation for cluster: test3
2017-12-22T09:16:20.569 - INFO - cfncluster.cfncluster - Creating stack named: cfncluster-test3
Status: cfncluster-test3 - CREATE_IN_PROGRESS        Status: SQS - CREATE_IN_PROGRESS                     Status: cfncluster-test3 - ROLLBACK_IN_PROGRESS```

and my config (us-west-2):

```[global]
update_check = true
sanity_check = true
cluster_template = test

[cluster test]
vpc_settings = testvpc
key_name = xx
master_instance_type = t2.micro
compute_instance_type = t2.micro```

**Comment by rajachan** [comment]
@chriskeraly We just made a new release of CfnCluster (v1.4.2) that has a fix for this problem among other updates and bugfixes. Feel free to reopen this should your problem persist.
