### ISSUE TITLE
mounting shared volume fails on c5d/m5d instance types

### ISSUE THREAD

**Issue by aqi-mph** [awslabs/cfncluster#415]
I'm consistently encountering failures when trying to launch a Centos7 cluster using any c5d or m5d instance type (e.g. c5d.9xlarge). Other instance types work fine. The relevant section of the master node's /var/log/cfn-init-cmd.log is below, which is from a run with the 1.5.0rc1 version (and the new AMI), though it fails at the same point with 1.4.2. Looks like it wants to find the shared EBS volume at /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de, but that symlink does not exist so it gives up. The volume vol-0d474bee16ac9a3de was actually mounted on at /dev/sdb on the master node according to the AWS web console, but looks like somehow its by-ebs-volumeid alias was not generated.
```
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:17-05:00] INFO: execute[attach_volume] sending run action to ruby_block[sleeping_for_volume] (immediate)
2018-06-14 17:59:19,155 P2182 [INFO] 	  * ruby_block[sleeping_for_volume] action run[2018-06-14T17:58:17-05:00] INFO: Processing ruby_block[sleeping_for_volume] action run (cfncluster::_master_base_config line 37)
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:17-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:22-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:27-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:32-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:37-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:42-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:47-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:52-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:58:57-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:59:02-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:59:07-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO] 	[2018-06-14T17:59:12-05:00] INFO: device /dev/disk/by-ebs-volumeid/vol-0d474bee16ac9a3de not ready - sleeping 5s
2018-06-14 17:59:19,155 P2182 [INFO]
2018-06-14 17:59:19,155 P2182 [INFO]
2018-06-14 17:59:19,155 P2182 [INFO] 	    ================================================================================
2018-06-14 17:59:19,155 P2182 [INFO] 	    Error executing action `run` on resource 'ruby_block[sleeping_for_volume]'
2018-06-14 17:59:19,155 P2182 [INFO] 	    ================================================================================
2018-06-14 17:59:19,155 P2182 [INFO]
2018-06-14 17:59:19,155 P2182 [INFO] 	    Timeout::Error
2018-06-14 17:59:19,155 P2182 [INFO] 	    --------------
2018-06-14 17:59:19,156 P2182 [INFO] 	    execution expired
2018-06-14 17:59:19,156 P2182 [INFO]
2018-06-14 17:59:19,156 P2182 [INFO] 	    Cookbook Trace:
2018-06-14 17:59:19,156 P2182 [INFO] 	    ---------------
2018-06-14 17:59:19,156 P2182 [INFO] 	    /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/libraries/helpers.rb:12:in `sleep'
2018-06-14 17:59:19,156 P2182 [INFO] 	    /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/libraries/helpers.rb:12:in `block in wait_for_block_dev'
2018-06-14 17:59:19,156 P2182 [INFO] 	    /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/libraries/helpers.rb:9:in `wait_for_block_dev'
2018-06-14 17:59:19,156 P2182 [INFO] 	    /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/recipes/_master_base_config.rb:39:in `block (2 levels) in from_file'
2018-06-14 17:59:19,156 P2182 [INFO]
2018-06-14 17:59:19,156 P2182 [INFO] 	    Resource Declaration:
2018-06-14 17:59:19,156 P2182 [INFO] 	    ---------------------
2018-06-14 17:59:19,156 P2182 [INFO] 	    # In /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/recipes/_master_base_config.rb
2018-06-14 17:59:19,156 P2182 [INFO]
2018-06-14 17:59:19,156 P2182 [INFO] 	     37: ruby_block "sleeping_for_volume" do
2018-06-14 17:59:19,156 P2182 [INFO] 	     38:   block do
2018-06-14 17:59:19,156 P2182 [INFO] 	     39:     wait_for_block_dev(dev_path)
2018-06-14 17:59:19,156 P2182 [INFO] 	     40:   end
2018-06-14 17:59:19,156 P2182 [INFO] 	     41:   subscribes :run, "execute[attach_volume]", :immediately
2018-06-14 17:59:19,156 P2182 [INFO] 	     42: end
2018-06-14 17:59:19,156 P2182 [INFO] 	     43:
2018-06-14 17:59:19,156 P2182 [INFO]
2018-06-14 17:59:19,156 P2182 [INFO] 	    Compiled Resource:
2018-06-14 17:59:19,156 P2182 [INFO] 	    ------------------
2018-06-14 17:59:19,156 P2182 [INFO] 	    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/recipes/_master_base_config.rb:37:in `from_file'
2018-06-14 17:59:19,157 P2182 [INFO]
2018-06-14 17:59:19,157 P2182 [INFO] 	    ruby_block("sleeping_for_volume") do
2018-06-14 17:59:19,157 P2182 [INFO] 	      action [:run]
2018-06-14 17:59:19,157 P2182 [INFO] 	      retries 0
2018-06-14 17:59:19,157 P2182 [INFO] 	      retry_delay 2
2018-06-14 17:59:19,157 P2182 [INFO] 	      default_guard_interpreter :default
2018-06-14 17:59:19,157 P2182 [INFO] 	      block_name "sleeping_for_volume"
2018-06-14 17:59:19,157 P2182 [INFO] 	      declared_type :ruby_block
2018-06-14 17:59:19,157 P2182 [INFO] 	      cookbook_name "cfncluster"
2018-06-14 17:59:19,157 P2182 [INFO] 	      recipe_name "_master_base_config"
2018-06-14 17:59:19,157 P2182 [INFO] 	      block #<Proc:0x0000000374b7d0@/etc/chef/local-mode-cache/cache/cookbooks/cfncluster/recipes/_master_base_config.rb:38>
2018-06-14 17:59:19,157 P2182 [INFO] 	    end
2018-06-14 17:59:19,157 P2182 [INFO]
2018-06-14 17:59:19,157 P2182 [INFO] 	    Platform:
2018-06-14 17:59:19,157 P2182 [INFO] 	    ---------
2018-06-14 17:59:19,157 P2182 [INFO] 	    x86_64-linux
```

**Comment by mauri-melato** [comment]
Thank you @aqi-mph for testing 1.5.0rc1 and the reporting.
I confirm the problem looks systematic with c5d instances and with all the Linux distributions.
We need to investigate further and we'll back to you with updates asap.

**Comment by mauri-melato** [comment]
Alas we couldn't dig into it in the last days but we acknowledge it's an important issue that needs to be addressed in a short term.
We'll keep you informed by updating this ticket.

**Comment by aqi-mph** [comment]
I've pulled and installed the latest version of cfncluster from github, but am still encountering this errror. Looking at the system logs, it appears to be grabbing cfncluster-cookbook from this url:

https://s3.amazonaws.com/cfncluster-resources-us-east-1/cookbooks/cfncluster-cookbook-1.5.1.tgz

That archive does not contain the fixes for this issue from https://github.com/awslabs/cfncluster-cookbook/pull/141.

How can I get it to grab a version of the cookbook that includes the fixes?

Thanks for you help.

**Comment by sean-smith** [comment]
Until we release the next version, you can use a custom cookbook: https://cfncluster.readthedocs.io/en/latest/custom_cookbook.html

**Comment by aqi-mph** [comment]
Thanks, that got me past this error but it now fails a few a bit farther along as indicated below; is there an obvious fix or should I open a separate issue?

    * append_if_no_line[export /home] action edit[2018-07-12T12:52:18-05:00] INFO: Processing append_if_no_line[export /home] action edit (/etc/chef/local-mode-cache/cache/cookbooks/nfs/providers/export.rb line 61)


      ================================================================================
      Error executing action `edit` on resource 'append_if_no_line[export /home]'
      ================================================================================

      NoMethodError
      -------------
      undefined method `escape_string' for #<Chef::Provider::AppendIfNoLine:0x0000000accabc8>

      Cookbook Trace:
      ---------------
      /etc/chef/local-mode-cache/cache/cookbooks/line/libraries/provider_append_if_no_line.rb:29:in `action_edit'
      /etc/chef/local-mode-cache/cache/cookbooks/nfs/providers/export.rb:73:in `block in class_from_file'

      Resource Declaration:
      ---------------------
      # In /etc/chef/local-mode-cache/cache/cookbooks/nfs/providers/export.rb

       61:       append_if_no_line "export #{new_resource.name}" do
       62:         path '/etc/exports'
       63:         line export_line
       64:         notifies :run, 'execute[exportfs]', :immediately
       65:       end
       66:     end

      Compiled Resource:
      ------------------
      # Declared in /etc/chef/local-mode-cache/cache/cookbooks/nfs/providers/export.rb:61:in `block in class_from_file'

      append_if_no_line("export /home") do
        action :edit
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :append_if_no_line
        cookbook_name "cfncluster"
        path "/etc/exports"
        line "/home 10.0.0.0/16(rw,sync,no_root_squash)\n"
      end

      Platform:
      ---------
      x86_64-linux

[2018-07-12T12:52:19-05:00] INFO: Running queued delayed notifications before re-raising exception

    ================================================================================
    Error executing action `create` on resource 'nfs_export[/home]'
    ================================================================================

    NoMethodError
    -------------
    append_if_no_line[export /home] (/etc/chef/local-mode-cache/cache/cookbooks/nfs/providers/export.rb line 61) had an error: NoMethodError: undefined method `escape_string' for #<Chef::Provider::AppendIfNoLine:0x0000000accabc8>

    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/line/libraries/provider_append_if_no_line.rb:29:in `action_edit'
    /etc/chef/local-mode-cache/cache/cookbooks/nfs/providers/export.rb:73:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/recipes/_master_base_config.rb

     89: nfs_export "/home" do
     90:   network node['cfncluster']['ec2-metadata']['vpc-ipv4-cidr-block']
     91:   writeable true
     92:   options ['no_root_squash']
     93: end
     94:

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/recipes/_master_base_config.rb:89:in `from_file'

    nfs_export("/home") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :nfs_export
      cookbook_name "cfncluster"
      recipe_name "_master_base_config"
      network "10.0.0.0/16"
      writeable true
      options ["no_root_squash"]
      directory "/home"
    end

    Platform:
    ---------
    x86_64-linux

[2018-07-12T12:52:19-05:00] INFO: Running queued delayed notifications before re-raising exception
[2018-07-12T12:52:19-05:00] INFO: template[/etc/ssh/sshd_config] sending restart action to service[ssh] (delayed)
Recipe: openssh::default
  * service[ssh] action restart[2018-07-12T12:52:19-05:00] INFO: Processing service[ssh] action restart (openssh::default line 94)
[2018-07-12T12:52:19-05:00] INFO: service[ssh] restarted

    - restart service service[ssh]
[2018-07-12T12:52:19-05:00] INFO: template[/etc/sysconfig/nfs] sending restart action to service[nfs-server] (delayed)
Recipe: nfs::server
  * service[nfs-server] action restart[2018-07-12T12:52:19-05:00] INFO: Processing service[nfs-server] action restart (nfs::server line 59)
[2018-07-12T12:52:19-05:00] INFO: service[nfs-server] restarted

    - restart service service[nfs-server]
[2018-07-12T12:52:19-05:00] INFO: file[/etc/sysctl.conf] sending restart action to service[network] (delayed)
Recipe: hostname::default
  * service[network] action restart[2018-07-12T12:52:19-05:00] INFO: Processing service[network] action restart (hostname::default line 63)
[2018-07-12T12:52:21-05:00] INFO: service[network] restarted

    - restart service service[network]

Running handlers:
[2018-07-12T12:52:21-05:00] ERROR: Running exception handlers
Running handlers complete
[2018-07-12T12:52:21-05:00] ERROR: Exception handlers complete
Chef Client failed. 45 resources updated in 01 minutes 08 seconds
[2018-07-12T12:52:21-05:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2018-07-12T12:52:21-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-12T12:52:21-05:00] ERROR: nfs_export[/home] (cfncluster::_master_base_config line 89) had an error: NoMethodError: append_if_no_line[export /home] (/etc/chef/local-mode-cache/cache/cookbooks/nfs/providers/export.rb line 61) had an error: NoMethodError: undefined method `escape_string' for #<Chef::Provider::AppendIfNoLine:0x0000000accabc8>
[2018-07-12T12:52:21-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by sean-smith** [comment]
What's happening is we've updated the version of chef in cookbook but not in the ami's (from the last release) that you're using.

There's no easy way to get around this until we do our next release. We'll update this issue when we do.

**Comment by aqi-mph** [comment]
Understood, can you provide an ETA for the next release?

Thanks.

**Comment by mauri-melato** [comment]
@aqi-mph  we've recently made available the release candidate of the new version that also fixes this issue.
It can be installed by `pip install --upgrade --pre cfncluster`. Please note the `--pre` option allows you to install the pre-release and development versions of a package.

If you're going to try it, please let us know how it goes.

Thanks!

**Comment by sanman-99** [comment]
I ran into the same exact issue when using c5d.9xlarge and centos7 as the image.  I upgraded to cfncluster-1.5.2rc3 as @mauri-melato stated and the issue has been resolved!  I was able to successfully deploy using c5d.9xlarge and centos7.

**Comment by aqi-mph** [comment]
I am able to run a c5d cluster with the new version of cfncluster, thanks
very much for the help and responsiveness.

**Comment by tfenne** [comment]
FWIW I just tried this too, but had less luck.  I ended up with version `cfncluster-1.5.3rc1` and tried to create a cluster of `m5d.12xlarge` instances, but when I did I ended up with no ephemeral storage mounted at all.  For now I've switched to using `m5.12xlarge` with more EBS storage.
