### ISSUE TITLE
cfncluster 1.5.2 configure fails on windows/cygwin

### ISSUE THREAD

**Issue by andyjones1982** [awslabs/cfncluster#474]
When I try to run:
`cfncluster configure `
it fails with the following message:

> Cluster Template [default]: 
> AWS Access Key ID []: 
> AWS Secret Access Key ID []: 
> Traceback (most recent call last):
>   File "/usr/bin/cfncluster", line 11, in <module>
>     sys.exit(main())
>   File "/usr/lib/python2.7/site-packages/cfncluster/cli.py", line 204, in main
>     args.func(args)
>   File "/usr/lib/python2.7/site-packages/cfncluster/cli.py", line 28, in configure
>     easyconfig.configure(args)
>   File "/usr/lib/python2.7/site-packages/cfncluster/easyconfig.py", line 133, in configure
>     aws_region_name = prompt('AWS Region ID', config.get('aws', 'aws_region_name') if config.has_option('aws', 'aws_region_name') else None, options=get_regions())
>   File "/usr/lib/python2.7/site-packages/cfncluster/easyconfig.py", line 53, in get_regions
>     ec2 = boto3.client('ec2')
>   File "/usr/lib/python2.7/site-packages/boto3/__init__.py", line 91, in client
>     return _get_default_session().client(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/boto3/session.py", line 263, in client
>     aws_session_token=aws_session_token, config=config)
>   File "/usr/lib/python2.7/site-packages/botocore/session.py", line 885, in create_client
>     client_config=config, api_version=api_version)
>   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 76, in create_client
>     verify, credentials, scoped_config, client_config, endpoint_bridge)
>   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 285, in _get_client_args
>     verify, credentials, scoped_config, client_config, endpoint_bridge)
>   File "/usr/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
>     endpoint_url, is_secure, scoped_config)
>   File "/usr/lib/python2.7/site-packages/botocore/args.py", line 111, in compute_client_args
>     service_name, region_name, endpoint_url, is_secure)
>   File "/usr/lib/python2.7/site-packages/botocore/client.py", line 358, in resolve
>     service_name, region_name)
>   File "/usr/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
>     partition, service_name, region_name)
>   File "/usr/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
>     raise NoRegionError()
> botocore.exceptions.NoRegionError: You must specify a region.
>

**Comment by andyjones1982** [comment]
Need to run 
`aws configure`
and set a region
before running 
`cfncluster configure`

Perhaps documentation should make this more clear?
