### ISSUE TITLE
cfncluster update throwing python errors on config file that worked for deploy

### ISSUE THREAD

**Issue by chrisdag** [awslabs/cfncluster#508]
Hi folks, 

I'm thinking that this error may be outside of cfncluster but was wondering if you've seen this traceback before. Google is not being super helpful. Much appreciated!

Wondering if my tags, JSON or even the post_install URL are somehow misquoted or altered? Not really sure where the parse error is happening 

Basic situation is python error when I try to do a simple stack update using a config file that worked perfectly fine for the actual cluster deployment ... 

It's gonna be something silly like quote handling or similar but I can't seem to find the specific cause 

Using version: 1.5.3
Python 2.7
Using latest awscli, boto and botocore packages

I get this error when I try to update an existing cluster, in this scenario all I'm trying to do is alter the max_queue_size value to a larger integer

This is the error I get when I try to update a cluster that successfully deployed without error:

```
Updating: GBLUPv2
Traceback (most recent call last):
  File "/usr/local/bin/cfncluster", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/cfncluster/cli.py", line 204, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/cfncluster/cli.py", line 46, in update
    cfncluster.update(args)
  File "/usr/local/lib/python2.7/dist-packages/cfncluster/cfncluster.py", line 167, in update
    Parameters=cfn_params, Capabilities=capabilities)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 131, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 115, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 360, in _emit
    aliased_event_name, kwargs, stop_on_response
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python2.7/dist-packages/botocore/signers.py", line 156, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python2.7/dist-packages/botocore/auth.py", line 358, in add_auth
    canonical_request = self.canonical_request(request)
  File "/usr/local/lib/python2.7/dist-packages/botocore/auth.py", line 305, in canonical_request
    body_checksum = self.payload(request)
  File "/usr/local/lib/python2.7/dist-packages/botocore/auth.py", line 267, in payload
    if request.body and hasattr(request.body, 'seek'):
  File "/usr/local/lib/python2.7/dist-packages/botocore/awsrequest.py", line 390, in body
    p = AWSPreparedRequest(self)
  File "/usr/local/lib/python2.7/dist-packages/botocore/awsrequest.py", line 428, in __init__
    self.prepare_body(original.data)
  File "/usr/local/lib/python2.7/dist-packages/botocore/awsrequest.py", line 481, in prepare_body
    self.body = urlencode(params, doseq=True)
  File "/usr/lib/python2.7/urllib.py", line 1355, in urlencode
    v = quote_plus(v.encode("ASCII","replace"))
  File "/usr/lib/python2.7/urllib.py", line 1306, in quote_plus
    return quote(s, safe)
  File "/usr/lib/python2.7/urllib.py", line 1299, in quote
    return ''.join(map(quoter, s))
KeyError: 104
```

My cluster config is nothing fancy, it looks like this:

```
[aws]
aws_region_name = us-east-1

[cluster GBLUPv2]
vpc_settings = vpc-XXX
key_name = usae-hpc-01
compute_instance_type = x1e.4xlarge
master_instance_type = m5.2xlarge
custom_ami = ami-XXX
initial_queue_size = 1
max_queue_size = 20
maintain_initial_size = true
scheduler = sge
cluster_type = ondemand
placement = cluster
proxy_server = http://XXX.XXX.XXX.XXX:8000
ephemeral_dir = /scratch
encrypted_ephemeral = false
master_root_volume_size = 50
compute_root_volume_size = 50
base_os = centos7
ec2_iam_role = ec2InstanceRole-HPC-CfnCluster
tags = { "Description" : "v2 Next-Gen (XX) Elastic autoscaling HPC grid via AWS CfnCluster", "Contact" : "chris.dagdigian@XX.com", "AnsibleTag" : "usae-XX-cfncluster-f
leet-v2", "Platform" : "usae-XX-hpc" }
pre_install = https://mirror.XX.org/pub/XXX/usae-hpc/scripts/pre_install-gblup-cfncluster.sh
extra_json = {
	      "yum":{
		"epel":{
		  "mirrorlist": "http://mirror.XX.org/pub/centos/mirrors/empty.txt",
		  "baseurl": "https://mirror.XX.org/pub/epel/7/x86_64/",
		  "sslverify": false,
		  "gpgcheck":  false
		}
	       },
               "poise-python": {
		 "python_package": {
		    "options": "-i http://mirror.XX.org/pypi/simple",
		    "install_options": "-i http://mirror.XX.org/pypi/simple"
		     }
	       },
	      "XXX":{
	        "avere-hostname": "usae-nfs.XX.org",
		"avere-nfs-mountopts": "rw,hard,intr,noatime,vers=3,_netdev",
		"avere-export": "/usae-s3/usae-hpc",
		"avere-mount": "/synhpc"
	      }
	     }

[vpc vpc-ee8d9c8b]
master_subnet_id = subnet-XX
compute_subnet_id = subnet-XX
vpc_security_group_id = sg-XX
additional_sg = sg-XX
use_public_ips = false
vpc_id = vpc-XX

[global]
update_check = true
sanity_check = true
cluster_template = GBLUPv2

```

**Comment by sean-smith** [comment]
It's fixed in https://github.com/awslabs/cfncluster/pull/497

**Comment by chrisdag** [comment]
Thank you so much! Will close this one.  Much appreciated.
